# Generated by Django 4.2.5 on 2023-09-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0002_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='goal',
            field=models.CharField(choices=[('Earn weight', 'Earn weight'), ('Lose weight', 'Lose weight'), ('Physical activity', 'Physical activity')], default='Earn weight', max_length=20),
        ),
    ]
